// Generated by CoffeeScript 1.6.3
(function() {
  var $;

  $ = jQuery;

  $.fn.extend({
    disableSelection: function() {
      return this.each(function() {
        if (typeof this.onselectstart !== 'undefined') {
          return this.onselectstart = function() {
            return false;
          };
        } else if (typeof this.style.MozUserSelect !== 'undefined') {
          return this.style.MozUserSelect = 'none';
        } else {
          return this.onmousedown = function() {
            return false;
          };
        }
      });
    }
  });

  $(document).ready(function() {
    var clearSlide, clickSlide, current_slide, i, nextProdNum, products, totalProdNum, _i;
    current_slide = null;
    nextProdNum = 10;
    totalProdNum = 30;
    clickSlide = function() {
      if (current_slide !== null) {
        current_slide.style.opacity = 1;
        current_slide.style.left = 0;
      }
      if (current_slide !== this) {
        current_slide = this;
      } else {
        current_slide = null;
      }
      if (current_slide !== null) {
        $.data(current_slide, "x", event.pageX);
        current_slide.style.opacity = 0.5;
        return setTimeout(clearSlide, 1300);
      }
    };
    clearSlide = function() {
      if (current_slide !== null) {
        current_slide.style.opacity = 1;
      }
      if (current_slide !== null) {
        current_slide.style.left = 0;
      }
      return current_slide = null;
    };
    products = document.getElementsByClassName('product');
    $('div p').disableSelection();
    for (i = _i = 0; _i <= 30; i = ++_i) {
      $(products[i]).height(150);
      $(products[i]).width(900);
      $(products[i]).bind('click', {}, clickSlide);
      if (i >= nextProdNum) {
        $(products[i]).hide();
      }
    }
    return $(document).mousemove(function(e) {
      var move;
      if (current_slide !== null) {
        move = (e.pageX - $.data(current_slide, "x")) * 1.5;
        current_slide.style.left = "" + move + "px";
        if (move > 1200) {
          nextProdNum++;
          $(current_slide).unbind('click');
          if (!(nextProdNum >= totalProdNum)) {
            $(products[nextProdNum]).show('slow');
          }
          $(products[i]).hide();
          setTimeout((function() {
            return $(current_slide).css("-webkit-transition-duration", "0");
          }), 300);
          setTimeout((function() {
            return $(current_slide).slideUp("slow");
          }), 300);
          return setTimeout((function() {
            return current_slide = null;
          }), 305);
        }
      }
    });
  });

}).call(this);
